# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'payform.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PayForm(object):
    def setupUi(self, PayForm):
        PayForm.setObjectName("PayForm")
        PayForm.resize(350, 500)
        self.label = QtWidgets.QLabel(PayForm)
        self.label.setGeometry(QtCore.QRect(30, 49, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_originPrice = QtWidgets.QLineEdit(PayForm)
        self.lineEdit_originPrice.setEnabled(False)
        self.lineEdit_originPrice.setGeometry(QtCore.QRect(100, 50, 131, 20))
        self.lineEdit_originPrice.setObjectName("lineEdit_originPrice")
        self.label_2 = QtWidgets.QLabel(PayForm)
        self.label_2.setGeometry(QtCore.QRect(30, 160, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_originPrice_2 = QtWidgets.QLineEdit(PayForm)
        self.lineEdit_originPrice_2.setEnabled(False)
        self.lineEdit_originPrice_2.setGeometry(QtCore.QRect(100, 160, 231, 20))
        self.lineEdit_originPrice_2.setObjectName("lineEdit_originPrice_2")
        self.label_3 = QtWidgets.QLabel(PayForm)
        self.label_3.setGeometry(QtCore.QRect(30, 290, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_originPrice_3 = QtWidgets.QLineEdit(PayForm)
        self.lineEdit_originPrice_3.setEnabled(False)
        self.lineEdit_originPrice_3.setGeometry(QtCore.QRect(100, 291, 131, 20))
        self.lineEdit_originPrice_3.setObjectName("lineEdit_originPrice_3")
        self.pushButton = QtWidgets.QPushButton(PayForm)
        self.pushButton.setGeometry(QtCore.QRect(130, 380, 80, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(PayForm)
        QtCore.QMetaObject.connectSlotsByName(PayForm)

    def retranslateUi(self, PayForm):
        _translate = QtCore.QCoreApplication.translate
        PayForm.setWindowTitle(_translate("PayForm", "Form"))
        self.label.setText(_translate("PayForm", "总计:"))
        self.label_2.setText(_translate("PayForm", "优惠："))
        self.label_3.setText(_translate("PayForm", "实付："))
        self.pushButton.setText(_translate("PayForm", "付款"))
